services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  nats_streaming:
    image: "nats-streaming:latest"
    ports:
      - 4222:4222
  app:
    depends_on:
      db:
        condition: service_healthy
      nats_streaming:
        condition: service_started
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080