services:
  nats_streaming:
    image: "nats-streaming:latest"
    ports:
      - 4222:4222
  app:
    depends_on:
      - nats_streaming
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    tty: true
    stdin_open: true