services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
  nats_streaming:
    image: "nats-streaming:latest"
    ports:
      - 4222:4222
  app:
    depends_on:
      - db
      - nats_streaming
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    tty: true
    stdin_open: true